pipeline:
  name: Kalyan-Harness-Git-Remote-Pipeline-2
  identifier: KalyanHarnessGitRemotePipeline2
  projectIdentifier: sunnyQA_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: CustomStage
        identifier: CustomStage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
